name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build web --dart-define=LAUNCHPAD_URL=${{ secrets.LAUNCHPAD_URL}} --dart-define=LAUNCHPAD_API=${{ secrets.LAUNCHPAD_API }} --dart-define=LAUNCHPAD_API_ME=${{ secrets.LAUNCHPAD_API_ME }} --dart-define=GAS_ENDPOINT=${{ secrets.GAS_ENDPOINT }}
      - name: publish
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          source: build/web/*
          target: ${{ secrets.HOST }}/public
          strip_components: 2
          overwrite: true
